@List_cursos = http://localhost:5012/curso
// Listar todos los cursos
GET {{List_cursos}}
Accept: application/json

###
@Curso_contenido = http://localhost:5012/curso/671b21d097475bd7f0f9de0a
// Obtener el contenido de un curso específico
GET {{Curso_contenido}}
Accept: application/json 

###
@Curso_detalle = http://localhost:5012/curso/671b21d097475bd7f0f9de0a/detalle
// Obtener los detalles de un curso específico
GET {{Curso_detalle}}
Accept: application/json

###

@Crear_curso = http://localhost:5012/curso
// Crear un nuevo curso
POST {{Crear_curso}}
Content-Type: application/json
Accept: application/json

{
    "id": "671b21d097475bd7f0f9de0a",
    "nombre": "Curso de Desarrollo de Aplicaciones Móviles",
    "descripcionBreve": "Aprende a desarrollar aplicaciones móviles desde cero.",
    "imagenPrincipal": "https://example.com/imagen_principal_movil.jpg",
    "imagenBanner": "https://example.com/imagen_banner_movil.jpg",
    "cantidadInscritos": 0,
    "unidades": [
        {
            "nombre": "Introducción a Desarrollo Móvil",
            "numeroOrden": 1,
            "clases": [
                {
                    "nombre": "Instalación de Herramientas",
                    "numeroOrden": 1,
                    "descripcion": "Aprende a instalar y configurar las herramientas necesarias para el desarrollo móvil.",
                    "videoUrl": "https://example.com/video_movil_instalacion",
                    "adjuntos": [
                        "https://example.com/adjunto1_movil",
                        "https://example.com/adjunto2_movil"
                    ]
                },
                {
                    "nombre": "Conceptos Básicos de Desarrollo Móvil",
                    "numeroOrden": 2,
                    "descripcion": "Conoce los conceptos básicos del desarrollo de aplicaciones móviles.",
                    "videoUrl": "https://example.com/video_movil_conceptos",
                    "adjuntos": [
                        "https://example.com/adjunto3_movil",
                        "https://example.com/adjunto4_movil"
                    ]
                }
            ]
        },
        {
            "nombre": "Desarrollo de Aplicaciones Android",
            "numeroOrden": 2,
            "clases": [
                {
                    "nombre": "Introducción a Android",
                    "numeroOrden": 1,
                    "descripcion": "Aprende los conceptos básicos del desarrollo de aplicaciones Android.",
                    "videoUrl": "https://example.com/video_android_introduccion",
                    "adjuntos": [
                        "https://example.com/adjunto5_android",
                        "https://example.com/adjunto6_android"
                    ]
                },
                {
                    "nombre": "Componentes de una Aplicación Android",
                    "numeroOrden": 2,
                    "descripcion": "Conoce los componentes principales de una aplicación Android.",
                    "videoUrl": "https://example.com/video_android_componentes",
                    "adjuntos": [
                        "https://example.com/adjunto7_android",
                        "https://example.com/adjunto8_android"
                    ]
                }
            ]
        }
    ]
}

###
@Login = http://localhost:5012/usuarios/login
// Iniciar sesión
POST {{Login}}
Content-Type: application/json
Accept: application/json

{
  "Email":"johndoe@example.com",
  "Password":"123"
}

###
@Register = http://localhost:5012/usuarios/register
// Registrarse
POST {{Register}}
Content-Type: application/json
Accept: application/json

{
  "Nombre":"Giacomo",
  "Email":"Giacomo@example.com",
  "Password":"123"
}

###
@IngresarCurso = http://localhost:5012/usuarios/ingresar-curso
// Ingresar a un usuario a un curso
POST {{IngresarCurso}}
Content-Type: application/json
Accept: application/json

{
  "IdUsuario": "navia@example.com",
  "IdCurso": "675617f25c4fe2ca9afe5468"
}
###

@VerCursosInscritos = http://localhost:5012/usuarios/cursos/navia@example.com
// Ver los cursos inscritos por un usuario
GET  {{VerCursosInscritos}}

###
@ActualizarEstadoCurso = http://localhost:5012/usuarios/actualizar-estado
PUT {{ActualizarEstadoCurso}}
Content-Type: application/json
Accept: application/json
// Actualizar el estado de un curso para un usuario

{
  "IdUsuario": "navia@example.com",
  "IdCurso": "675617f25c4fe2ca9afe5468",
  "Progreso": 100,
  "Estado": "COMPLETADO",
  "Completado": true
}

### 
@CrearComentarioCurso = http://localhost:5012/comentariocurso
// Crear un comentario para un curso
POST {{CrearComentarioCurso}}
Content-Type: application/json
Accept: application/json

{
  "cursoId": "671b21d097475bd7f0f9de0a",
  "autor": "navia@example.com",
  "titulo": "Excelente curso",
  "detalle": "Este curso es muy completo y bien estructurado.",
  "valoracion": 5,
  "me_gusta": 10,
  "no_me_gusta": 0
}

###

@Comentarios_curso = http://localhost:5012/comentariocurso/671b21d097475bd7f0f9de0a
// Obtener los comentarios de un curso específico
GET {{Comentarios_curso}}
Accept: application/json

###